version: '3.7'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - mdb:/var/lib/mysql
    expose:
        - "3306"
    networks:
      - app-network
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wp:/var/www/html
    expose:
      - "9000"
    networks:
      - app-network
    depends_on:
      - mariadb
    restart: on-failure
  
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wp:/var/www/html
    ports:
      - 443:443
    networks:
      - app-network
    depends_on:
      - wordpress
    restart: on-failure

networks:
  app-network:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt