
services:
  nginx:
    container_name: nginx-container
    build: requirements/nginx/
    image: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - docker-network
    volumes:
      - wordpress:/var/www/html

  mariadb:
    container_name: mariadb-container
    build: requirements/mariadb/
    image: mariadb
    restart: always
    networks:
      - docker-network
    volumes:
      - db:/var/lib/mysql
    env_file: .env
    secrets:
      - db_root_password
      - db_user
      - db_password

  wordpress:
    container_name: wordpress-container
    build: requirements/wordpress/
    image: wordpress
    restart: always
    depends_on:
      - mariadb
    networks:
      - docker-network
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_password
      - db_user
      - ftp_password

  ftp:
    container_name: ftp-container
    build: ./requirements/ftp/.
    image: ftp
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/hylim/ftp/files
    env_file:
      - .env
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    networks:
      - docker-network
    restart: always
    secrets:
      - ftp_password

  adminer:
    container_name: adminer-container
    build: ./requirements/adminer/.
    image: adminer
    depends_on:
      - mariadb
    ports:
      - "600:80"
    networks:
      - docker-network
    restart: always

  redis:
    container_name: redis-container
    build: ./requirements/redis/.
    image: redis
    volumes:
     - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - docker-network
    restart: always

  static-web:
    container_name: static-web-container
    build: ./requirements/static-web/.
    image: static-web
    depends_on:
      - wordpress
    networks:
      - docker-network
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      # device: /Users/limhyeontaek/data/wordpress
      device: /home/hylim/data/wordpress
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      # device: /Users/limhyeontaek/data/db
      device: /home/hylim/data/db
      o: bind


networks:
  docker-network:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
