http {
    server {
        listen 80;
        server_name ${DOMAIN_NAME};
    
        return 301 https://$host$request_uri;
        # HTTP에서 HTTPS로 리다이렉트
    }
    
    server {
        listen 443 ssl;
        # 443 포트에서 SSL을 사용하여 NGINX 서버를 리슨합니다.
    
        server_name ${DOMAIN_NAME};
        # 환경 변수 DOMAIN_NAME을 사용하여 서버 이름을 설정합니다.
    
        ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
        # SSL 인증서 경로를 설정합니다.
    
        ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
        # SSL 인증서 키 경로를 설정합니다.
    
        ssl_protocols TLSv1.2 TLSv1.3;
        # 사용할 SSL 프로토콜을 설정합니다.
    
        ssl_prefer_server_ciphers on;
        # 서버 암호화를 우선하도록 설정합니다.
    
        ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256';
        # 사용할 SSL 암호화 방식을 설정합니다.
    
        location / {
            root /var/www/html;
            # 웹 서버의 루트 디렉토리를 설정합니다.
    
            index index.html index.htm;
            # 기본 인덱스 파일을 설정합니다.
    
            try_files $uri $uri/ /index.php$is_args$args;
            # 요청된 파일이 존재하지 않을 경우, index.php로 요청을 전달합니다.
        }
    
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            # PHP-FPM 설정 파일을 포함합니다.
    
            fastcgi_pass wordpress:9000;
            # WordPress 서비스의 PHP-FPM 포트로 요청을 전달합니다.
    
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            # PHP 파일의 전체 경로를 설정합니다.
    
            include fastcgi_params;
            # FastCGI 매개변수 파일을 포함합니다.
        }
    }
}