server {
	listen 33771;
	server_name example.com;
	root /33771/;
	index bb.html;
	error_page 400 /400.html;
	error_page 403 /403.html;
	error_page 404 /404.html;
	error_page 405 /405.html;
	error_page 409 /409.html;
	error_page 413 /413.html;
	error_page 415 /415.html;
	error_page 422 /422.html;

	location /400.html {
		root /errors/
	}
	location /403.html {
		root /errors/
	}
	location /404.html {
		root /errors/
	}
	location /405.html {
		root /errors/
	}
	location /409.html {
		root /errors/
	}
	location /413.html {
		root /errors/
	}
	location /415.html {
		root /errors/
	}
	location /422.html {
		root /errors/
	}
}

server {
	listen 33777;
	server_name localhost;

	autoindex on;
	
	error_page 400 /400.html;
	error_page 403 /403.html;
	error_page 404 /404.html;
	error_page 405 /405.html;
	error_page 409 /409.html;
	error_page 413 /413.html;
	error_page 415 /415.html;
	error_page 422 /422.html;

	location /400.html {
		root /errors/
	}
	location /403.html {
		root /errors/
	}
	location /404.html {
		root /errors/
	}
	location /405.html {
		root /errors/
	}
	location /409.html {
		root /errors/
	}
	location /413.html {
		root /errors/
	}
	location /415.html {
		root /errors/
	}
	location /422.html {
		root /errors/
	}

	client_max_body_size 10M;
}

server {
	listen 33777;
	server_name example.com;
	allow_methods GET POST;
	root /33777/;
	index bb.html;
	error_page 400 /400.html;
	error_page 403 /403.html;
	error_page 404 /404.html;
	error_page 405 /405.html;
	error_page 409 /409.html;
	error_page 413 /413.html;
	error_page 415 /415.html;
	error_page 422 /422.html;

	location /400.html {
		root /errors/
	}
	location /403.html {
		root /errors/
	}
	location /404.html {
		root /errors/
	}
	location /405.html {
		root /errors/
	}
	location /409.html {
		root /errors/
	}
	location /413.html {
		root /errors/
	}
	location /415.html {
		root /errors/
	}
	location /422.html {
		root /errors/
	}
}
